// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzuZuxqrGyVeUP0bmkpbisoDr21pV7564',
    appId: '1:750365490230:web:18c638809026a425126c97',
    messagingSenderId: '750365490230',
    projectId: 'msap-9d5c4',
    authDomain: 'msap-9d5c4.firebaseapp.com',
    storageBucket: 'msap-9d5c4.appspot.com',
    measurementId: 'G-TS9VSJQ1B2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDks2PrTr7MTM6c97nVAKjcfHujNcrwkSs',
    appId: '1:750365490230:ios:dc5855c018916594126c97',
    messagingSenderId: '750365490230',
    projectId: 'msap-9d5c4',
    storageBucket: 'msap-9d5c4.appspot.com',
    iosBundleId: 'com.ZOOMMER.msap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDks2PrTr7MTM6c97nVAKjcfHujNcrwkSs',
    appId: '1:750365490230:ios:dc5855c018916594126c97',
    messagingSenderId: '750365490230',
    projectId: 'msap-9d5c4',
    storageBucket: 'msap-9d5c4.appspot.com',
    iosBundleId: 'com.ZOOMMER.msap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzuZuxqrGyVeUP0bmkpbisoDr21pV7564',
    appId: '1:750365490230:web:2ddc8df6208ba4d0126c97',
    messagingSenderId: '750365490230',
    projectId: 'msap-9d5c4',
    authDomain: 'msap-9d5c4.firebaseapp.com',
    storageBucket: 'msap-9d5c4.appspot.com',
    measurementId: 'G-J6DDBVX6N4',
  );
}
